function [] = GNU_GPL_License(license_str_p1, license_str_p3)

license_str_p2 = ...
    {'This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.' ...
    '' ...
    'This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.' ...
    '' ...
    'You should have received a copy of the GNU General Public License along with this program.  If not, see http://www.gnu.org/licenses/.' ...
    ''};

if isempty(license_str_p3)
    license_str = [license_str_p1 license_str_p2];
else
    license_str = [license_str_p1 license_str_p2 license_str_p3];
end

hFig = figure('Name', 'License', 'Menubar','none', 'Toolbar','none');
hPan = uipanel(hFig, 'Title','', ...
    'Units','normalized', 'Position',[0.05 0.05 0.9 0.9]);
hEdit = uicontrol(hPan, 'Style', 'edit', 'FontSize',10, 'FontName', 'Consolas', ...
    'Min',0, 'Max',2, 'HorizontalAlignment','left', ...
    'Units','normalized', 'Position',[0 0 1 1], ...
    'String',license_str);
end